# PyTorch Tensor Functions


#### Let's try to explore 5 interesting functions related to PyTorch tensors


#### What is PyTorch? 
It’s a Python-based scientific computing package targeted at two sets of audiences:

A replacement for NumPy to use the power of GPUs
a deep learning research platform that provides maximum flexibility and speed

- torch.rand
- torch.trace
- torch.reshape
- torch.eye
- torch.unique
- torch.unique_consecutive
- torch.normal

In [1]:
# Import torch and other required modules
#!conda install pytorch cpuonly -c pytorch -y

Solving environment: ...working... done

# All requested packages already installed.



In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.rand()

This function returns a tensor filled with random numbers from a uniform distribution on the interval (0,1).


In [2]:
# Example 1 - working
torch.rand(9)

tensor([0.8257, 0.6649, 0.6506, 0.2102, 0.3933, 0.0189, 0.3276, 0.4554, 0.6036])

In the above cell, we can observe that we got a tensor vector of 9 elements in the interval [0,1)

In [3]:
# Example 2 - working
torch.rand(3,3)

tensor([[0.3851, 0.1115, 0.0887],
        [0.1349, 0.3144, 0.6057],
        [0.7807, 0.3588, 0.4047]])

Here, we get a tensor of shape 3x3 with elements in the interval [0,1)

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
torch.rand(5, dtype = torch.int32)

RuntimeError: _th_uniform_ not supported on CPUType for Int

## Function 2 - torch.trace()

Returns the sum of the elements of the diagonal of the input 2-D matrix.


In [5]:
# Example 1 - working
x = torch.arange(1., 10.).view(3, 3)
print(x)
torch.trace(x)


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


tensor(15.)

As we can see, the function takes in the input 2D tensor and computes the sum of the elements along the diagonal.

In [6]:
# Example 2 - working
y = torch.randint(high=50,size=(1,25)).view(5,5)
print(y)
torch.trace(y)

tensor([[30, 39, 49, 13, 24],
        [ 9, 35, 47,  1, 33],
        [20, 37, 32, 20,  0],
        [ 8,  7, 34, 31, 16],
        [24, 45,  6, 31, 27]])


tensor(155)

As we can see, the function takes in the input 2D tensor and computes the sum of the elements along the diagonal.



In [7]:
# Example 3 - breaking (to illustrate when it breaks)
torch.trace(torch.randint(high=100,size=(2,)))

RuntimeError: invalid argument 1: expected a matrix at C:\cb\pytorch_1000000000000\work\aten\src\TH/generic/THTensorMoreMath.cpp:303

This function only expects a 2D matrix and giving anything else will break it.Here, we gave a 1D array.

## Function 3 — torch.reshape()
Returns a tensor with the same data and number of elements as input, but with the specified shape. 

In [8]:
# Example 1 - working

a = torch.arange(9.)
print(a)
torch.reshape(a, (3, 3))



tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])


tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

The above example explains how one can reshape a given tensor into a 3x3 tensor.


In [9]:
# Example 2 - working

b = torch.tensor([[0, 1], [2, 3], [5,7], [8,9]])
print(b)
torch.reshape(b, (-1,))


tensor([[0, 1],
        [2, 3],
        [5, 7],
        [8, 9]])


tensor([0, 1, 2, 3, 5, 7, 8, 9])

In the above example, we are reducing the shape of a 2D tensor to a 1D array.

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(c)
torch.reshape(c, (2,3))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


RuntimeError: shape '[2, 3]' is invalid for input of size 9

The above example fails because we have not mentioned correct dimensions for target tensor for the given tensor of size 9.

This function is useful when we have to transform the tensors from one size to other based on the application.

## Function 4 — torch.eye()


Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [11]:
# Example 2 - working

torch.eye(9)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Returns a diagonal matrix of 9x9

In [12]:
torch.eye(5,1)

tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.]])

Returns a diagonal matrix of 5x1

Might come in handy when you have to do matrix multiplication

## Function 5 - torch.unique()

torch.unique() only outputs all unique values out of an input tensor. 

In [13]:
# Example 1 - Working
A = torch.tensor([1, 1, 2, 2, 3, 0])
torch.unique(A)

tensor([0, 1, 2, 3])

The above example shows us the unique elements of the tensor.

In [14]:
# Example 2 - Working

B = torch.eye(8)
print(B)
torch.unique(B)

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]])


tensor([0., 1.])

The above example shows us the unique elements of the tensor.

In [15]:
output = torch.unique(torch.tensor([1, 3, 2, 3], dtype=torch.long))
print(output)

tensor([1, 2, 3])


## Function 5.1 - torch.unique_consecutive()

Eliminates all but the first element from every consecutive group of equivalent elements.


In [16]:
# Example 1 - Working
x = torch.tensor([1, 1, 2, 2, 3, 1, 1, 2, 4, 4, 4, 5, 6, 7, 8, 8])
print(x)
output = torch.unique_consecutive(x)
output

tensor([1, 1, 2, 2, 3, 1, 1, 2, 4, 4, 4, 5, 6, 7, 8, 8])


tensor([1, 2, 3, 1, 2, 4, 5, 6, 7, 8])

These two functions may be simple but can be used to filter data, create frequency tables and find a pattern in your data.

## Function 6 - torch.normal()

Returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.

The mean is a tensor with the mean of each output element’s normal distribution

The std is a tensor with the standard deviation of each output element’s normal distribution

In [17]:
# Example 1 - Working

torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([ 2.0580,  2.7422,  2.1098,  3.9449,  6.3202,  6.5172,  7.5367,  7.7494,
         8.7392, 10.1302])

The above example explains the formulation of a tensor whose elements are drawn from normal distribution.


In [18]:
# Example 2 - working
torch.normal(mean=0.5, std=torch.arange(1., 9.))

tensor([-1.2501, -1.1083,  1.9794, -3.1798,  5.2533,  5.6019,  0.5029,  1.9030])

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(0.5, 0, -0.1))

RuntimeError: inconsistent tensor, std and mean are not broadcastable and have different number of elements, expected mean [10] and std [5] to have same number of elements)

The above example explains the formulation of a tensor whose elements are drawn from normal distribution. However it failed as the number elements requested is different for mean and standard deviation.

## Conclusion

In this notebook, we have looked at some of the basic and useful functions in the PyTorch library.


## Reference Links

Provide links to your references and other interesting articles about tensors

Official documentation for torch.Tensor: https://pytorch.org/docs/stable/tensors.html


In [20]:
!pip install jovian --upgrade --quiet


In [21]:
import jovian


In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


[jovian] Error: Failed to detect notebook filename. Please provide the correct notebook filename as the "filename" argument to "jovian.commit".


In [27]:
cd

C:\Users\Nikhit
